config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'application#home'
  get '/about-andrews-exotics', to: 'static#about'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/facebook' , as: 'fb_login'
  get '/auth/facebook/callback', to: 'sessions#create_fb'

  resources :vehicles, only: [:index, :show]
  #post '/vehicles', to: 'admin/vehicles#create'
  #patch '/vehicles/:id', to: 'admin/vehicles#update'
  
  resources :appointments
  resources :sessions
  
  resources :customers do
    resources :appointments
  end

  namespace :admin do
    resources :vehicles
    resources :vehicle_sales
    resources :appointments
    resources :employees
    resources :sessions
    resources :menus, only: [:index]
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
  end

end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :appointments
    has_many :employees, through: :appointments
    has_many :vehicle_sales
    has_many :vehicles, through: :vehicle_sales
    
    has_secure_password

    validates :name, :email, presence: true
    validates :email, uniqueness: true
    validates_confirmation_of :password

    accepts_nested_attributes_for :appointments
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

    before_action :get_customer, only: [:show, :edit, :update, :destroy]
    
    def new
        @customer = Customer.new
    end

    def create
        @customer = Customer.new(cust_params)
        if @customer.save
            session[:user_id] = @customer.id
            redirect_to customer_path(@customer), notice: "Successfully Created Account!"
        else
            render :new
        end
    end

    def show
    end

    def edit
    end

    def update
        if valid_customer?
            if @customer.update(skip_password_attribute)
                redirect_to customer_path(@customer), notice: "Successfully Updated Account!"
            else
                render :edit
            end
        else
            redirect_to root_path, alert: "Please login to update your account."
        end
    end

    def destroy
    end

    private

    def skip_password_attribute
        if params[:customer][:password].blank? && params[:customer][:password_confirmation].blank?
            cust_params.except(:password, :password_confirmation)
        else
            cust_params
        end
    end
    
    def cust_params
        params.require(:customer).permit(:name, :address, :city, :state, :zip, :email, :password, :password_confirmation, :phone)
    end  
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/views/customers/_customer.html.erb
<head>
<style>
    body {
        background-image: url('/images/Carrera_gt.jpg');
        background-repeat: no-repeat;
        background-size: cover;
    }
</style>
</head>

<body>

<% if customer.errors.any? %>
    <div class="alert alert-danger">
    <h2>
        <%= pluralize(customer.errors.count, "Error") %>
        prohibited this account from being saved:
    </h2>
 
    <ul>
        <% customer.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
    </div>
<% end %>

<div class='container-md w-75 bg-light rounded'>
    
    <%= form_for customer do |f| %>
            <span class='row col'>Full Name: <%= f.text_field :name, class: 'form-control'%></span>
            <p class='row col'>Street Address: <%= f.text_field :address, class: 'form-control' %></p>
            <div class='row'>
                <p class='col'>City: <%= f.text_field :city %></p>
                <p class='col'>State: <%= f.text_field :state %></p>
                <p class='col'>Zip: <%= f.text_field :zip %></p>
            </div>
            <div class='row'>
                <span class='col'>Email: <%= f.text_field :email %></span>
                <p class='col'>Phone: <%= f.text_field :phone %></p>
            </div>
            <div class='row'>
                <span class='col'>Password: <%= f.password_field :password %></span>
                <span class='col'>Re-enter Password: <%= f.password_field :password_confirmation %></span>
            </div>
            <%= f.submit class: 'row col btn btn-primary' %>
        </div>
    <% end %>
</div>
</body>

app/views/customers/edit.html.erb
<div class='row'>
        <h2 class='col text-white' align='center'>Edit Profile</h2>
    </div>
    
<%= render partial: 'customer', locals: {customer: @customer} %>

app/views/customers/new.html.erb
<div class= 'container-sm w-25 right'>
    <h2 class='text-white' align='center'>Login With</h2>
    <div align='center'>
        <%= link_to 'Facebook', fb_login_path, class: 'btn btn-primary' %>
        <%= link_to 'Google', login_path, class: 'btn btn-info' %>
    </div>
</div><br />

<div class='row'>
    <h5 class='col text-white' align='center'>Or Create an Account to Make Appointments</h5>
</div>

<%= render partial: 'customer', locals: {customer: @customer} %>

app/views/customers/show.html.erb
<div class='container w-50'>

    <h2 align='center'>Account Details</h2>

    <% if @customer.uid.blank? %>
        <p>Account Type: Website Account</p>
    <% else %>
        <p>Account Type: Facebook Login</p>
    <% end %>

    <p>Name: <%= @customer.name %></p>

    <p>Address: <%= @customer.address %></p>
   
    <p>
        City: <%= @customer.city %>
        State: <%= @customer.state %>
        Zip: <%= @customer.zip %>
    </p>

    <p>
        Email: <%= @customer.email %>
        Phone: <%= @customer.phone %>
    </p>

    <%= link_to "Edit Account Details or Change Password", edit_customer_path(@customer), class: 'btn btn-primary' %>
    
</div>