config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'application#home'
  get '/about-andrews-exotics', to: 'static#about'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/facebook' , as: 'fb_login'
  get '/auth/facebook/callback', to: 'sessions#create_fb'

  resources :vehicles, only: [:index, :show]
  #post '/vehicles', to: 'admin/vehicles#create'
  #patch '/vehicles/:id', to: 'admin/vehicles#update'
  
  resources :appointments
  resources :sessions
  
  resources :customers do
    resources :appointments
  end

  namespace :admin do
    resources :vehicles
    resources :vehicle_sales
    resources :appointments
    resources :employees
    resources :sessions
    resources :menus, only: [:index]
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
  end

end

app/models/appointment.rb
class Appointment < ApplicationRecord

    include ActiveModel::Validations

    belongs_to :customer
    belongs_to :employee

    validates :description, :appt_date, :appt_time, presence: true

    validates_with ApptDateValidator
    validates_with ApptTimeValidator
  
    scope :order_by_date, -> {order(appt_date: :asc)}
    
end

app/controllers/admin/appointments_controller.rb
class Admin::AppointmentsController < ApplicationController
    layout 'admin'

    before_action :get_employee, only: [:new, :create, :edit, :update]

    def new
        if @employee.access_level < 200
            redirect_to admin_menus_path, alert: 'You do not have access to create an appointment!'
        else
            @appointment = @employee.appointments.build(appt_time: Time.new(2000))
            @customers = Customer.all
            @employees = Employee.all
        end
    end

    def create
        if !valid_employee?
            redirect_to admin_login_path, alert: "Please Login to create appointments!"
        else
            @selected_employee = Employee.find(params[:appointment][:employee_id].to_i)
            @appointment = @selected_employee.appointments.build(appt_params)
            if @appointment.save
                redirect_to admin_appointments_path, notice: "Appointment successfully created!"
            else
                @customers = Customer.all
                @employees = Employee.all
                render :new
            end
        end
    end

    def edit
        if !valid_employee?
            redirect_to admin_login_path, alert: 'Please login to edit appointments!'
        else
            if @employee.access_level < 200
                redirect_to admin_menus_path, alert: "You do not have access to create an appointment!"
            else
                @appointment = Appointment.find(params[:id])
                @customers = Customer.all
                @employees = Employee.all
            end
        end
    end

    def update
        if !valid_employee?
            redirect_to admin_login_path, alert: "Please Login to create appointments!"
        else
            #@selected_employee = Employee.find(params[:appointment][:employee_id].to_i)
            @appointment = Appointment.find(params[:id])
            if @appointment.update(appt_params)
                redirect_to admin_appointments_path, notice: "Appointment successfully updated!"
            else
                @customers = Customer.all
                @employees = Employee.all
                render :edit
            end
        end

    end

    def index
        if !valid_employee?
            redirect_to admin_login_path, alert: "Please Login to view appointments!"
        end
        @appointments = Appointment.order_by_date
    end

    def destroy
        if !valid_employee?
            redirect_to admin_login_path, alert: "Please Login to delete appointments!"
        elsif
            if @employee.access_level < 300
                redirect_to admin_appointments_path, alert: "You do not have access to delete appointments!"
            end
        else 
            @appointment = Appointment.find(params[:id])
            if @appointment.delete
                redirect_to admin_appointments_path, notice: "Appointment successfully deleted."
            else
                redirect_to admin_appointments_path, alert: "Unable to delete appointment."
            end
        end
    end
    private

    def appt_params
        params.require(:appointment).permit(:description, :appt_type, :employee_id, :customer_id, :appt_date, :appt_time)
    end
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

before_action :get_appointment, only: [:show, :edit, :update, :destroy]

    def new
        if nested_valid_customer?(params[:customer_id].to_i)
            @appointment = get_customer.appointments.build(appt_type: params[:appt_type], appt_time: Time.new(2000))
            @employees = Employee.all
        else
            redirect_to root_path, alert: "Please login to make an appointment."
        end
    end

    def create
        if nested_valid_customer?(params[:customer_id].to_i)
            @appointment = get_customer.appointments.build(appt_params)
            if @appointment.save
                redirect_to customer_appointments_path(@appointment.customer), notice: "Successfully created appointment!"
            else
                @employees = Employee.all
                render :new
            end
        else
            redirect_to root_path, alert: "Please login to make an appointment."
        end
    end

    def index
        if nested_valid_customer?(params[:customer_id].to_i)
            @appointments = get_customer.appointments.all
        else
            flash.now[:alert] = "Test - NEED TO LOGIN"
            redirect_to login_url, alert: "Please login to view appointments."
        end
    end

    def show
        if !nested_valid_customer?(params[:customer_id].to_i) ||
            !get_customer.appointments.include?(@appointment)
            redirect_to root_path, alert: "Please login to view appointments."
        end
    end

    def edit 
        if nested_valid_customer?(params[:customer_id].to_i)
            get_customer
            @employees = Employee.all
            if !@appointment = @customer.appointments.find_by(id: params[:id])
                redirect_to root_path, alert: "Please login to change appointments."
            end
        else
            redirect_to root_path, alert: "Please login to change appointments."
        end
    end

    def update
        if nested_valid_customer?(@appointment.customer_id) &&
            get_customer.appointments.include?(@appointment)
            if @appointment.update(appt_params)
                redirect_to customer_appointment_path(get_customer.id, @appointment), notice: "Successfully updated appointment!"
            else
                @employees = Employee.all
                render :'edit'
            end
        else
            redirect_to root_path, alert: "Please login to change appointments."
        end
    end

    def destroy
        if nested_valid_customer?(@appointment.customer_id) &&
            get_customer.appointments.include?(@appointment)
            if @appointment.delete
                redirect_to customer_appointments_path(get_customer.id), notice: "Your appointment was successfully cancelled."
            else
                redirect_to root_path, alert: "Please login to cancel appointments."
            end
        end
    end

    private
    
    def get_appointment
        @appointment = Appointment.find_by(id: params[:id].to_i)
    end

    def appt_params
        params.require(:appointment).permit(:appt_type, :description,
            :appt_date, :appt_time, :employee_id)
    end
end

app/helpers/admin/appointments_helper.rb
module Admin::AppointmentsHelper
end

app/helpers/appointment_helper.rb
module AppointmentHelper
end

app/views/appointments/_appointment.html.erb
<% if appt.errors.any? %>
    <div class="alert alert-danger">
    <h2>
        <%= pluralize(appt.errors.count, "Error") %>
        prohibited this appointment from being saved:
    </h2>

    <ul>
        <% appt.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
    </div>
<% end %>

<div class='container w-50'>
<%= form_for appt do |f| %>
    <%= hidden_field_tag 'customer_id', appt.customer.id %>

    <div class='row form-group'>
        <span>Appointment Type: </span>
        <span><%= f.select :appt_type, [['Sales', 'sales'], ['Service', 'service']] %></span>
        
    </div>

    <div class='row form-group'>Please Enter Brief Description: <%= f.text_area :description, class: 'form-control' %></div>
   
    <div class='row form-group'>
        <span>Date: <%= f.text_field :appt_date, type: 'date' %></span>
        <span>Time: <%= f.text_field :appt_time, type: 'time',
        value: Time.parse(appt.appt_time).strftime("%H:%M"), min: "09:00", max: "18:00" %></span>
    </div>

    <div class='row form-group'>
        <p>Select Advisor: <%= f.collection_select :employee_id, @employees, :id, :name %></p>
    </div>

    <%= f.submit class: 'btn btn-primary' %>
<% end %>

</div>

app/views/appointments/index.html.erb
<div class='container w-75'>
    <h2 align='center'>Current Appointments</h2>
    <table class='table'>
        <tr>
            <th scope='col'>Date</th>
            <th scope='col'>Time</th>
            <th scope='col'>Description</th>
            <th scope='col'>Advisor</th>
            <th scope='col'>Type</th>
            <th scope='col'>Options</th>
        </tr>
        
        <% @appointments.each do |appt| %>
            <tr>
                <td><%= appt.appt_date %></td>
                <td><%= Time.parse(appt.appt_time).strftime("%H:%M")%></td>
                <td><%= appt.description %></td>
                <td>
                    <% if appt.employee.nil? %>
                        Employee Not Found
                    <% else %>
                        <%= appt.employee.name %>
                    <% end %>
                </td>
                <td><%= appt.appt_type %></td>
                <td><%= link_to "View/Edit/Cancel", edit_customer_appointment_path(appt.customer_id, appt.id), class: 'btn btn-primary' %></td>
            </tr>
        <% end %>
    </table>
</div>

    <div class='container w-75'>
        <div class='row'>
        <div class='card col-md'>
            <%= link_to new_customer_appointment_path(current_customer, appt_type: 'sales') do %>
                <h4 align='center'>Make Sales Appointment</h4>
                <img class='img-fluid' src='/images/key.jpg' alt='key'>
            <% end %> 
        </div>

        <div class='card col-md'>
        <%= link_to new_customer_appointment_path(current_customer, appt_type: 'service') do %>
            <h4 align='center'>Make Service Appointment</h4>
            <img class='img-fluid' src='/images/auto_repair2.jpg' alt='repair'>
            <img class='img-fluid' src='/images/auto_repair.jpg' alt='repair'>
        <% end %>
        
        </div>
    </div>
</div>

app/views/appointments/show.html.erb
<div class='container w-50'>

    <h2 align='center'>Appointment Details</h2>

    <p>Appointment Type: <%= @appointment.appt_type %></p>

    <p>Description: <%= @appointment.description %></p>
   
    <p>
        Date: <%= @appointment.appt_date %>
        Time: <%= @appointment.appt_time %>
    </p>

    <p>
        Advisor: <%= @appointment.employee.name %>
    </p>

    <%= link_to "Back to Appointments Listing", customer_appointments_path(@appointment.customer_id), class: 'btn btn-primary' %></td>

</div>