config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  
  root to: 'application#home'
  get '/about-andrews-exotics', to: 'static#about'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/facebook' , as: 'fb_login'
  get '/auth/facebook/callback', to: 'sessions#create_fb'

  resources :vehicles, only: [:index, :show]
  #post '/vehicles', to: 'admin/vehicles#create'
  #patch '/vehicles/:id', to: 'admin/vehicles#update'
  
  resources :appointments
  resources :sessions
  
  resources :customers do
    resources :appointments
  end

  namespace :admin do
    resources :vehicles
    resources :vehicle_sales
    resources :appointments
    resources :employees
    resources :sessions
    resources :menus, only: [:index]
    get '/login', to: 'sessions#new'
    post '/login', to: 'sessions#create'
    delete '/logout', to: 'sessions#destroy'
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord

    include ActiveModel::Validations

    belongs_to :customer
    belongs_to :employee

    validates :description, :appt_date, :appt_time, presence: true

    validates_with ApptDateValidator
    validates_with ApptTimeValidator
  
    scope :order_by_date, -> {order(appt_date: :asc)}
    
end

app/models/carname.rb
class Carname < ApplicationRecord
    has_many :vehicles

    scope :vehicle_models, -> {includes(:vehicles).where.not(vehicles: {id: nil})}

end

app/models/customer.rb
class Customer < ApplicationRecord
    has_many :appointments
    has_many :employees, through: :appointments
    has_many :vehicle_sales
    has_many :vehicles, through: :vehicle_sales
    
    has_secure_password

    validates :name, :email, presence: true
    validates :email, uniqueness: true
    validates_confirmation_of :password

    accepts_nested_attributes_for :appointments
end

app/models/employee.rb
class Employee < ApplicationRecord
    has_many :appointments
    has_many :customers, through: :appointments
    has_many :vehicle_sales
    has_many :vehicles, through: :vehicle_sales
    
    has_secure_password

    validates :name, :email, presence: true
    validates :email, uniqueness: true
    validates_confirmation_of :password  
end

app/models/make.rb
class Make < ApplicationRecord
    has_many :vehicles

    scope :vehicle_makes, -> { includes(:vehicles).where.not(vehicles: {id: nil})}

end

app/models/photo.rb
class Photo < ApplicationRecord
    belongs_to :vehicle
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
    belongs_to :make
    belongs_to :carname
    has_many :photos
    has_one :vehicle_sale
    
    accepts_nested_attributes_for :make
    accepts_nested_attributes_for :carname
    accepts_nested_attributes_for :photos, reject_if: proc {|field| field[:link_to_photo].blank?}

    validates :price, :year, :mileage, :description, presence: true

    scope :older, -> {where("year<2000")}
    scope :newer, -> {where("year>2015")}
    scope :order_by_price, -> { order(price: :asc)}
    scope :order_by_make, -> { joins(:make).merge(Make.order(name: :asc))}
    scope :order_by_year, -> {order(year: :desc)}

    def make_attributes=(make_hash)
        unless make_hash[:name].empty?
            make_instance = Make.find_or_create_by(make_hash)
            self.make = make_instance
            self.save
        end 
    end

    def carname_attributes=(name_hash)
        unless name_hash[:name].empty?
            model_instance = Carname.find_or_create_by(name_hash)
            self.carname = model_instance
            self.save
        end 
    end
    
    def self.search_vehicle(search)
        where("vehicle_search LIKE ?", "%#{search}%")
    end
    
    def self.by_make(make_id)
        where(make: make_id)
    end

    def self.by_model(model_id)
        where(carname: model_id)
    end
   
    def self.sold
        where(sold: true)
    end

    def self.not_sold
        where(sold: false)
    end

    def vehicle_select
        "Vehicle ID: #{id} | #{year} | #{make.name} | #{carname.name}"
    end
end

app/models/vehicle_sale.rb
class VehicleSale < ApplicationRecord

    belongs_to :customer
    belongs_to :employee
    has_one :vehicle

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        @customer = Customer.find_by(email: params[:email])
        if @customer && @customer.authenticate(params[:password])
            session[:user_id] = @customer.id 
            redirect_to root_path, notice: "Login Successful!"
        else
            redirect_to login_path, alert: "Invalid email or password"
        end
    end

    def create_fb
        @customer = Customer.find_or_create_by(uid: auth['uid']) do |c|
            c.name = auth['info']['name']
            c.email = auth['info']['email']
            random_password = SecureRandom.base64(15)
            c.password = random_password
            c.password_confirmation = random_password
        end
        session[:user_id] = @customer.id
        redirect_to root_path
    end

    def destroy
        session.delete(:user_id)
        redirect_to root_path
    end

    private

    def auth
        request.env['omniauth.auth']
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
    before_action :find_vehicle, only: [:show]

    def index
        if !params[:search].blank?
            @vehicles = Vehicle.search_vehicle(params[:search].downcase).not_sold
        elsif !params[:make].blank?
            @vehicles = Vehicle.by_make(params[:make]).not_sold
        elsif !params[:carname].blank?
            @vehicles = Vehicle.by_model(params[:carname]).not_sold
        elsif !params[:order_by].blank?
            case params[:order_by]
            when 'price'
                @vehicles = Vehicle.order_by_price.not_sold
            when 'make'
                @vehicles = Vehicle.order_by_make.not_sold
            when 'year'
                @vehicles = Vehicle.order_by_year.not_sold
            else
                @vehicles = Vehicle.not_sold
            end
        elsif !params[:select].blank?
            if params[:select] == 'older'
                @vehicles = Vehicle.older.not_sold
            elsif params[:select] == 'newer'
                @vehicles = Vehicle.newer.not_sold
            end
        else
            @vehicles = Vehicle.not_sold
        end
        @makes = Make.vehicle_makes
        @carnames = Carname.vehicle_models
    end

    def show
        @options = @vehicle.options.split(", ")
    end

    private

    def find_vehicle
        @vehicle = Vehicle.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointment_helper.rb
module AppointmentHelper
end

app/helpers/carname_helper.rb
module CarnameHelper
end

app/helpers/customer_helper.rb
module CustomerHelper
end

app/helpers/employee_helper.rb
module EmployeeHelper
end

app/helpers/make_helper.rb
module MakeHelper
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def logged_in?
        !!current_customer
    end

    def current_customer
        @customer = Customer.find_by(id: session[:user_id])
    end

    def employee_logged_in?
        !!current_employee
    end

    def current_employee
        @employee = Employee.find_by(id: session[:empl_id])
    end
end

app/helpers/vehicle_helper.rb
module VehicleHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>AutoDealer</title>
    
    <style>
      .field_with_errors {
        display: inline-block;
        border: 3px solid red;
      }
    </style>

    <!-- Bootstrap Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
      
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
      <nav class='navbar navbar-expand-md navbar-dark bg-primary'>
        <div class='container-fluid'>
          <div class='navbar-header'>
            <%= link_to image_tag('/images/logo2.jpg', height:50), root_path, class: 'navbar-brand' %>
          </div>
          <ul class="nav navbar-nav">
            <li class="nav-item">
              
            </li>
            <li class="nav-item">
              <%= link_to "Inventory (Customer View)", vehicles_path, class: 'nav-link active' %>
            </li>
            <li class='nav-item'>
              <%= link_to "Admin Menu", admin_menus_path, class: 'nav-link active' %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <% if employee_logged_in? %>
              <li class='nav-item'>
                <%= link_to "Logged In As: #{current_employee.name} ", edit_admin_employee_path(current_employee), class: 'nav-link active' %>
              </li>
              <li class='nav-item'>
                <%= button_to 'Logout', admin_logout_path, method: 'delete', class: 'text-white btn btn-link active' %>
              </li>
              <% else %>  
                <li class='nav-item'>
                    <%= link_to "Employee Login", admin_login_path, class: 'nav-link active' %>
                </li>
                <% end %>
            </li>
            
          </ul>
        </div>
      </nav>
      
    <!-- Flash Messages Display -->

    <div class='container w-50'>
      <% flash.each do |type, msg| %>
        <% if type == 'notice' %>
          <div class='alert alert-success' align='center'>
            <%= msg %>
          </div>
        <% elsif type == 'alert' %>
          <div class='alert alert-danger' align='center'>
            <%= msg %>
          </div>
        <% end %>
      <% end %>
    </div>

    

    <%= yield %>

    <!-- Bootstrap Optional JavaScript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>AutoDealer</title>
    
    <style>
      .field_with_errors {
        display: inline-block;
        border: 3px solid red;
      }
    </style>

    <!-- Bootstrap Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
      
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    
      <nav class='navbar navbar-expand-md navbar-dark bg-primary'>
        <div class='container-fluid'>
          <div class='navbar-header'>
            <%= link_to image_tag('/images/logo2.jpg', height:50), root_path, class: 'navbar-brand' %>
          </div>
          <ul class="nav navbar-nav">
            <li class="nav-item">
              <div class='container-fluid'>
        
                <%= form_tag(vehicles_path, method: 'get', class: 'form-inline') do %>
                  <%= text_field_tag :'search', nil, class:'form-control mr-sm-2', placeholder:"Search Inventory" %>
                  <button class="active btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                <% end %>
              </div>
            </li>
            <li class="nav-item">
              <%= link_to "Inventory", vehicles_path, class: 'nav-link active' %>
            </li>
            <li class='nav-item'>
              <% if logged_in? %>
              <%= link_to "Appointments", customer_appointments_path(current_customer.id), class: 'nav-link active' %>
              <% else %>
              
              <%= link_to "Appointments", appointments_path, class: 'nav-link active' %>
              <% end %>
              </li>
            <li class='nav-item'>
            <%= link_to "Admin Menu", admin_menus_path, class: 'nav-link active' %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <% if logged_in? %>
              <li class='nav-item'>
                <%= link_to "Logged In As: #{current_customer.name} ", edit_customer_path(current_customer), class: 'nav-link active' %>
              </li>
              <li class='nav-item'>
                <%= button_to 'Logout', logout_path, method: 'delete', class: 'text-white btn btn-link active' %>
              </li>
              <% else %>  
                <li class='nav-item dropleft'>
                  <button class='btn btn-primary dropdown-toggle' id='dropdownMenuLink' type='button' data-toggle="dropdown" data-target="#navbarDropdown" aria-haspopup="true" aria-expanded="false">
                    Login
                  </button>
                  <div class='dropdown-menu' id='navbarDropdown' aria-labelledby='dropdownMenuLink'>
                    <%= link_to "Login Via Website", login_path, class: 'dropdown-item' %>
                    <%= link_to "Login Via Facebook", fb_login_path, class: 'dropdown-item' %>
                  </div>
                </li>
                <li class='nav-item dropleft'>
                  <button class='btn btn-primary dropdown-toggle' id='dropdownMenuLink' type='button' data-toggle="dropdown" data-target="#navbarDropdown2" aria-haspopup="true" aria-expanded="false">
                    Create Account
                  </button>
                  <div class='dropdown-menu' id='navbarDropdown2' aria-labelledby='dropdownMenuLink'>
                    <%= link_to "Create Account", new_customer_path, class: 'dropdown-item' %> 
                    <%= link_to "Login Via Facebook", fb_login_path, class: 'dropdown-item' %>
                  </div> 
              </li>
                <% end %>
            </li>
            
          </ul>
        </div>
      </nav>
      
    <!-- Flash Messages Display -->

    <div class='container w-50'>
      <% flash.each do |type, msg| %>
        <% if type == 'notice' %>
          <div class='alert alert-success' align='center'>
            <%= msg %>
          </div>
        <% elsif type == 'alert' %>
          <div class='alert alert-danger' align='center'>
            <%= msg %>
          </div>
        <% end %>
      <% end %>
    </div>

    

    <%= yield %>

    <!-- Bootstrap Optional JavaScript -->
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    
    </body>
  
</html>